#!/usr/bin/env bash

if ! command -v ghc &> /dev/null
then
  echo "Please install ghc from https://www.haskell.org/ghc/download.html, and then re-run this command."
  exit 1
else
  ghc -O3 ./lambda.hs
  rm lambda.hi lambda.o
  exit 0
fi

