#!/usr/bin/env bash

if ! command -v ghc &> /dev/null
then
  echo "Please install ghc from https://www.haskell.org/ghc/download.html, and then re-run this command."
  exit 1
else
  ghc ./lambda.hs
fi

